call plug#begin()
"Plug 'sakhnik/nvim-gdb'
Plug 'kien/ctrlp.vim'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/nerdcommenter'
Plug 'jlanzarotta/bufexplorer'
Plug 'rhysd/vim-clang-format'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-sensible'
Plug 'lyuts/vim-rtags'
Plug 'neomake/neomake'
Plug 'saltzm/nvim_config'
call plug#end()
